# Generated by Django 5.0.2 on 2024-03-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_created_at_material_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='превью'),
        ),
    ]
