# Generated by Django 5.0.2 on 2024-03-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.BooleanField(default=True, verbose_name='Активная версия'),
        ),
    ]
