# Generated by Django 5.0.2 on 2024-03-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='version',
        ),
    ]
