# Generated by Django 4.2.11 on 2024-04-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('set_published', 'Can publish posts'), ('set_description', 'Can change description'), ('set_category', 'Can change category')], 'verbose_name': 'продукты', 'verbose_name_plural': 'продукт'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
